### ISSUE TITLE
Rewrite the build system

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1509]
It's worth rewriting the codebase build system to use webpack, babel, postcss, plus their associated loaders and plugins, to cleanly do a lot of things that are currently (necessarily) not as clean as the most modern approaches allow for.

## Tasks that are necessary "before" a rewrite is even possible:

- [ ] [refactor the gulp tasks so that toggling tasks is manageable](https://github.com/mozilla/teach.mozilla.org/issues/1558)
- [x] [refactor `jsx` files to more modular forms (single class per file with `require()`s, stateless components as straight up JSX, etc)](https://github.com/mozilla/teach.mozilla.org/issues/1571)

## Tasks that need doing as part of the rewrite
- [x] [rewrite the React components to match modern form](https://github.com/mozilla/teach.mozilla.org/issues/1550)
- [x] [remove static bindings for components that can just be required where needed](https://github.com/mozilla/teach.mozilla.org/issues/1578)
- [x] [rewrite the serving system to React-Router 1.0](https://github.com/mozilla/teach.mozilla.org/issues/1501)

## Tasks that will be good to follow up with
- [ ] [use the new mofo-style linter rules](https://github.com/mozilla/teach.mozilla.org/issues/1557)
- [ ] [add GreenKeeper for keeping our dependencies up to date](https://github.com/mozilla/teach.mozilla.org/issues/1495)
- [x] [get the Node version we require on Travis.js updated to something sensible](https://github.com/mozilla/teach.mozilla.org/issues/1564)
- [ ] [refactor how we use `<IconLinks>`, because it's not DRY enough](https://github.com/mozilla/teach.mozilla.org/issues/1584)
- [ ] [Clean up use of Illustration with divs](https://github.com/mozilla/teach.mozilla.org/issues/1585)

**Comment by hannahkane** [comment]
@Pomax - how do you want to manage this ticket moving forward? Should we keep it in the current milestone? Or, are we done with it for now (my understanding), and therefore we should take it out of the current milestone - either to close or to pick up again later?

**Comment by Pomax** [comment]
I'd say let's take it out of any milestone but keep it around as a tracking ticket. It's not longer a thing that feels tied to specific heartbeats, but still appropriate to work through when there's a lull in the workloads.

**Comment by alanmoo** [comment]
I feel like we're hitting a point where we really need to address this. With l10n tasks added, the testing system is starting to break (and take forever to do so), and it's hard to debug where it's breaking due to the Rube Goldberg-esque build system. Thoughts @pomax @hannahkane @alicoding?

**Comment by hannahkane** [comment]
Let's discuss in Going Global and Local Impact kick-off meetings today.

**Comment by Pomax** [comment]
we spent an entire heartbeat cleaning up the build system, this tracking ticket is now obsolete.
