### ISSUE TITLE
rewrite gulp tasks to npm scripts where possible

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#1558]
our gulp file's super complex, we need to simplify. Ideally to a situation where there isn't a gulp file at all, and tasks (other than watches) are simple piped command chains.

- [x] [give each task its own runner file, with only the requirements and inputs it needs](https://github.com/mozilla/teach.mozilla.org/issues/1559)
- [x] [find and externalise all webpack configs (we have many)](https://github.com/mozilla/teach.mozilla.org/issues/1561)
- [ ] [map each single gulp talk to an npm script](https://github.com/mozilla/teach.mozilla.org/issues/1562)
- [ ] [map each compound gulp task to a compound npm script](https://github.com/mozilla/teach.mozilla.org/issues/1563)

**Comment by Pomax** [comment]
gulp is gone~
