### ISSUE TITLE
Clubs Pages Implementation Tracking Issue

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2013]
## What's left to do

**Left before Launch**
* [x] Make sure all new elements are responsive
* [x] Resolve missing icons in narrow mode for the tabs
* [x] Need to figure out how to incorporate the new Clubs Application form stuff - with help from @Pomax 
* [x] Obtain & add content for initial Featured Updates section - #2061
  * Or remove if not needed for launch
* Once it hits staging
  * [ ] Design QA @sabrinang 
  * [ ] Content QA by Clubs Team

**Big Stuff**
* [x] @gvn to update the Carousel so it works in the Teach site -  [issue](https://github.com/mozilla/learning.mozilla.org/issues/2060) 
  * [x] Add content from Caro into the Carousel
  * It all used to live in the clubs.jsx page which no longer exists in the new tabbed branch code
* [x] Convert all the text to use the localization system\
  * [x] Clubs Guides - localizing Category labels for now only, will revist post-launch
  * [x] Club Captain Carousel

**Styling & Tweaks**
* [x] Review Carousel with 'live' content with @sabrinang and make adjustments / file issues as needed.
* [x] Figure out border-radius for tabs
  * cc @sabrinang
* [x] Standardize link & outlined button color (should be same)
  * cc @sabrinang 
* [x] Fix yellow button styling on the "Start" page
* [x] Figure out what to do with Footer
  * Will be ditching the footer for now until a site-wide change
* [x] Triple social share area
  * [x] Link the whole box to the destination
  * [x] Add slight scale effect on hover

**Follow up / not critical**
* [ ] Luke & Gavin will identify places and content types that belong in the Mofo bootstrap theme and place them there accordingly

**Some handy links**
* [Clubs Designs on Redpen](https://redpen.io/p/rb14e4c0eb3594f430)
* [Mofo-ui Repo](https://github.com/mozilla/mofo-ui)
* [Bootstrap](http://getbootstrap.com/)

**Glossary**
* **mofo-ui** - external library of interactive components like menus and carousels
* **bootstrap** - external library of basic layout and content styles used on mofo sites

**Comment by flukeout** [comment]
@gvn - Let me know if this makes sense and reflects what we talked about earlier today.

**Comment by flukeout** [comment]
@sabrinang Have you given thought to the mobile/narrow view of this Testimonial component?

![image](https://cloud.githubusercontent.com/assets/25212/17121401/640ebe0c-5288-11e6-9cb3-8790aa21de89.png)

**Comment by flukeout** [comment]
Sounds like @gvn has already done some mobile styling for this component - let us know when it hits the mofo-ui demo page and we can take a look there and provide feedback as needed.

**Comment by gvn** [comment]
@flukeout I made a new branch with a 3 tab scaffold for you to populate.

It's here:
https://github.com/mozilla/learning.mozilla.org/tree/clubs-big-kahuna

We should probably meet quickly to discuss, but this should get you started!

**Comment by flukeout** [comment]
Thanks @gvn - I'll give you a ping for a walkthrough before stand tomorrow sometime.

**Comment by hannahkane** [comment]
tagging @hannahkane to get updates

**Comment by flukeout** [comment]
Feature request for @gvn 

**Can we**
* Remember what tab you were last on so if you refresh, it opens that same tab?
* Update the address bar to show the tab that you are currently looking at
  * ``/clubs`` for the first tab
  * ``/clubs/start`` for the second tab
  * ``/clubs/running`` for third tab
* Make it so that the correct tab opens when you load one of the URLs above?

**Comment by flukeout** [comment]
Styling questions for @sabrinang 

* What is the hover state for non-selected tabs?

Will go over these in person later, but noting them down so I don't forget.

**Comment by gvn** [comment]
Let's do the deep linking as a follow up once this is landed.

**Comment by flukeout** [comment]
Need link for, don't see it in the [content doc](https://docs.google.com/document/d/1yQgNldfjwGE_lT0JEeTDsgzNJTceWh58i6VsUyishAo/edit#)

![image](https://cloud.githubusercontent.com/assets/25212/17413114/c6026aba-5a34-11e6-9a03-dc9dad7e1016.png)

**Comment by hannahkane** [comment]
Oh wow. I totally dropped the ball on that. The plan for that page was originally to build it with Calypso. Now that that's not going to happen, I'll file a follow-up ticket to build that page. In the meantime, I'd suggest we drop that sentence.

**Comment by flukeout** [comment]
Will do, thanks!

**Comment by flukeout** [comment]
**Design QA Review with Sabrina**

* [ ] Figure out border-radius for tabs
* [ ] Standardize link & outlined button color (should be same)
* [ ] Link the "See Example" buttons to the URLs listed in the doc
* [ ] Figure out what to do with Featured Updates
  * Julia or Caro to source content.
* [ ] Fix yellow button styling on the "Start" page
* [ ] Figure out what to do with Footer
* [ ] Sort out the 'visited' link style, it's darker and underlined still
* [ ] Triple social share area
  * [ ] Link the whole box to the destination
  * [ ] Add slight scale effect on hover

**Comment by gvn** [comment]
I opened an issue on Learning for the carousel integration. I don't think it's a mofo-ui issue since the carousel works fine on Science. It seems to be a problem with how Learning is compiled with Webpack, but I'm having a hard time nailing it down.

**Comment by sabrinang** [comment]
@flukeout 
Border radius for tabs - It should be similar to all buttonborder-radius on the learning site `border-radius: 4px;`

Link colour - On the learning site link colour is `#337AB7` 

Footer - Yes, we do not need to introduce the dark footer and continue to use the existing side nav footer.

**Comment by flukeout** [comment]
Thanks @sabrinang - I made the changes.

**Comment by flukeout** [comment]
@sabrinang Since our mofo-ui component needs icons for the narrow versions of the tabs, I've decided to use the following...

![image](https://cloud.githubusercontent.com/assets/25212/17603174/d0dc5230-5fc4-11e6-9165-0a735d0eef74.png)

* About clubs (info icon)
* Start a club (start flag icon)
* Running your club (guide icon since there are resources there)

Let me know if you'd like to change any of these.

**Comment by flukeout** [comment]
@gvn Okay - I think this is READY! and my branch has all of the latest. What's the best course of action?

**Comment by gvn** [comment]
Sweet! Just make a PR to the `master` branch of the `mozilla` repo and flag someone (probably me?) for a review.

**Comment by flukeout** [comment]
Closing as PR is now merged. Will file follow-up issue to QA on staging.
